server:
  port: 8080

spring:
  application:
    name: renote-backend
  datasource:
    url: jdbc:mysql://localhost:3306/renote?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.renote.backend.mapper: debug
